[general]
import = [
    #"~/.my_desktop/catppuccin-alacritty-themes/catppuccin-latte.toml"
    #"~/.my_desktop/catppuccin-alacritty-themes/catppuccin-latte.toml"
    #"~/.my_desktop/catppuccin-alacritty-themes/catppuccin-latte.toml"
    #"~/.my_desktop/catppuccin-alacritty-themes/catppuccin-latte.toml"
]

[window]
padding = { x = 5, y = 5 }
dimensions = { columns = 100, lines = 35 }

[font]
size = 10

[terminal]
shell = { program = "/usr/bin/zsh" }
